DROP TABLE HAVI_KPI;
DROP TABLE TRANZAKCIO;
DROP TABLE HITELKARTYA;
DROP TABLE HITELSZAMLA;
DROP TABLE UGYFEL;
DROP TABLE HUSEG_PREF_MCC;
DROP TABLE MCC_KOD;
DROP TABLE DEVIZA;
DROP TABLE TRANZ_TIPUS;
DROP TABLE KARTYA_TIPUS;
DROP TABLE HUSEG_PROGRAM;
DROP TABLE SZEGMENTUMOK;

CREATE TABLE SZEGMENTUMOK (
    szegmens_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nev VARCHAR2(50) NOT NULL,
    leiras VARCHAR2(200)
);

CREATE TABLE HUSEG_PROGRAM (
    huseg_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nev VARCHAR2(50) NOT NULL,
    alap_cashback NUMBER(5,2)
);

CREATE TABLE KARTYA_TIPUS (
    kartya_tipus_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    megnevezes VARCHAR2(50) NOT NULL,
    kibocsato VARCHAR2(50),
    kartyadij NUMBER(10,2),
    keret_min NUMBER(12),
    keret_max NUMBER(12)
);

CREATE TABLE TRANZ_TIPUS (
    tranz_tipus_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nev VARCHAR2(50) NOT NULL
);

CREATE TABLE DEVIZA (
    deviza_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devizanem VARCHAR2(3) NOT NULL,
    arfolyam NUMBER(10,4) NOT NULL
);

CREATE TABLE MCC_KOD (
    mcc_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod VARCHAR2(4) UNIQUE NOT NULL,
    megnevezes VARCHAR2(100)
);

CREATE TABLE HUSEG_PREF_MCC (
    huseg_id NUMBER REFERENCES HUSEG_PROGRAM(huseg_id),
    mcc_id NUMBER REFERENCES MCC_KOD(mcc_id),
    extra_cashback_szazalek NUMBER(5,2),
    PRIMARY KEY (huseg_id, mcc_id)
);

CREATE TABLE UGYFEL (
    ugyfel_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    szegmens_id NUMBER REFERENCES SZEGMENTUMOK(szegmens_id),
    vezeteknev VARCHAR2(100),
    keresztnev VARCHAR2(100),
    szul_datum DATE,
    irszam VARCHAR2(10),
    varos VARCHAR2(100),
    utca VARCHAR2(100),
    hazszam VARCHAR2(20)
);

CREATE TABLE HITELSZAMLA (
    szamla_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    szamlaszam VARCHAR2(24) UNIQUE NOT NULL,
    ugyfel_id NUMBER REFERENCES UGYFEL(ugyfel_id),
    huseg_id NUMBER REFERENCES HUSEG_PROGRAM(huseg_id),
    nyitas_datum DATE DEFAULT SYSDATE,
    bezar_datum DATE,
    hitelkeret NUMBER(12,2),
    egyenleg NUMBER(12,2) DEFAULT 0,
    statusz VARCHAR2(20) DEFAULT 'AKTIV'
);

CREATE TABLE HITELKARTYA (
    kartya_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    szamla_id NUMBER REFERENCES HITELSZAMLA(szamla_id),
    kartya_tipus_id NUMBER REFERENCES KARTYA_TIPUS(kartya_tipus_id),
    kartyaszam VARCHAR2(16) UNIQUE NOT NULL,
    gyartas DATE,
    aktivalas DATE,
    ervenyesseg DATE
);

CREATE TABLE TRANZAKCIO (
    tranz_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kartya_id NUMBER REFERENCES HITELKARTYA(kartya_id),
    mcc_id NUMBER REFERENCES MCC_KOD(mcc_id),
    tranz_tipus_id NUMBER REFERENCES TRANZ_TIPUS(tranz_tipus_id),
    deviza_id NUMBER REFERENCES DEVIZA(deviza_id),
    akt_arfolyam NUMBER(10,4),
    datum TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    osszeg NUMBER(12,2) NOT NULL,
    konvertalt_osszeg NUMBER(12,2)
);

CREATE TABLE HAVI_KPI (
    kpi_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    szamla_id NUMBER REFERENCES HITELSZAMLA(szamla_id),
    honap NUMBER(6),
    zaro_egyenleg_huf NUMBER(12,2),
    keretkihaszn_index NUMBER(10,2),
    kalkulalt_kamat NUMBER(12,2),
    kalkulalt_dijak NUMBER(12,2),
    kalkulalt_cashback NUMBER(12,2),
    tranzakciok_szama NUMBER,
    vasarlasi_volumen NUMBER(12,2),
    kp_felvetel_volumen NUMBER(12,2),
    befizetett_osszeg NUMBER(12,2),
    fizetesi_hanyad NUMBER(5,2),
    kesedelmes_napok NUMBER DEFAULT 0,
    szamla_statusz VARCHAR2(20)
);
